name: gpt_router_env
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h6c40b1e_6
  - ca-certificates=2025.7.15=hecd8cb5_0
  - expat=2.7.1=h6d0c2b6_0
  - libcxx=19.1.7=haebbb44_3
  - libffi=3.4.4=hecd8cb5_1
  - ncurses=6.5=h923df54_0
  - openssl=3.0.17=hee2dfae_0
  - pip=25.2=pyhc872135_1
  - python=3.11.13=hbff2529_0
  - readline=8.3=h49f2429_0
  - setuptools=78.1.1=py311hecd8cb5_0
  - sqlite=3.50.2=hc8b0dd6_1
  - tk=8.6.15=h3a5a201_0
  - wheel=0.45.1=py311hecd8cb5_0
  - xz=5.6.4=h46256e1_1
  - zlib=1.2.13=h4b97444_1
  - pip:
      - annotated-types==0.7.0
      - anyio==4.11.0
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - cramjam==2.11.0
      - distro==1.9.0
      - fastparquet==2024.11.0
      - filelock==3.20.0
      - fsspec==2025.10.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - jinja2==3.1.6
      - jiter==0.11.1
      - joblib==1.5.2
      - markupsafe==3.0.3
      - mpmath==1.3.0
      - networkx==3.5
      - numpy==2.3.4
      - openai==2.7.1
      - packaging==25.0
      - pandas==2.3.3
      - pillow==12.0.0
      - pyarrow==22.0.0
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - sentence-transformers==5.1.2
      - six==1.17.0
      - sniffio==1.3.1
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tokenizers==0.22.1
      - torch==2.2.2
      - tqdm==4.67.1
      - transformers==4.57.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
prefix: /Users/fateme/miniconda3/envs/gpt_router_env
